# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MorfoCuencas
                                 A QGIS plugin
 Este plugin permite hacer una caracterización de una cuenca morfométrica...
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-17
        copyright            : (C) 2021 by Sebastian Sierra, David Duarte
        email                : ssierrab@correo.udistrital.edu.co, djduartea@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MorfoCuencas class from file MorfoCuencas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MorfoCuencas import MorfoCuencas
    return MorfoCuencas(iface)
